### ISSUE TITLE
skin for cracked player 

### ISSUE THREAD

**Issue by BaXyy** [Solar-Tweaks/Solar-Tweaks#1146] opened 2023-04-28 14:59 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by HypedDomi** [comment] 2023-04-28 19:53
Duplicate of https://github.com/Solar-Tweaks/Solar-Tweaks/issues/963

**Closed by HypedDomi** 2023-04-28 19:53 UTC
Labels: enhancement
