### ISSUE TITLE
Jre Zulu not downloading...

### ISSUE THREAD

**Issue by CallMeSpark** [Solar-Tweaks/Solar-Tweaks#1158] opened 2023-05-01 18:22 UTC
**Describe the bug**
When i am trying to download jre Zulu it isn't downloading just showing download again and again over....

**To Reproduce**
1. Go to solar tweaks launcher 
2. Click on settings
3. Scroll down to jre downloader
4. Delete jre Zulu if you have if not then click on download and see the error.

**Expected behavior**

**Actual behaviour**
When i M trying to download jre Zulu it isn't downloading it is just showing download option again and again...

**Screenshots**

**Environment (please complete the following information):**
 - OS: windows 10
 - Launcher Version latest 
 - Engine Version 
 - Solar Stats Version 

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by Quotions** [comment] 2023-05-01 19:22
#1144

**Comment by HypedDomi** [comment] 2023-05-01 20:37
Duplicate of https://github.com/Solar-Tweaks/Solar-Tweaks/issues/1144

**Closed by HypedDomi** 2023-05-01 20:37 UTC
Labels: bug

**Comment by CallMeSpark** [comment] 2023-05-02 07:25
ik i did its still same i tried redownloading solar tweaks and lunar client and still the jre aint downloading @HypedDomi

**Comment by HypedDomi** [comment] 2023-05-02 08:25
> ik i did its still same i tried redownloading solar tweaks and lunar client and still the jre aint downloading @HypedDomi

Please use the issue i mentioned
