### ISSUE TITLE
Crashed when Command Aliases are used

### ISSUE THREAD

**Issue by Pragnyayadav** [Solar-Tweaks/Solar-Tweaks#931] opened 2023-03-01 06:16 UTC
**Describe the bug**
I created a command aliase for Party invite on a cracked server(play.pika-network.net), also i have a premium account.
Whenever i use it my game crashes pretty much on every server (cracked or premium) with code CRASH-c7e14d47-1f51-4d73-a60a-f70152040ef2

**To Reproduce**
1. Go to any server
2. Click on use the command aliase(for me its /p for /p inv)

**Expected behavior**
It should invite the person to my party

**Actual behaviour**
A blank loading screen (that we see when it says loggin in when connecting to a server) and then game crashes

**Screenshots**
![image](https://user-images.githubusercontent.com/63871463/222059447-a28b6233-9ad9-48e9-94c1-e6f94c38adae.png)
![image](https://user-images.githubusercontent.com/63871463/222059540-9a5507e4-4c94-4d5b-a3e9-7d58c61ad4e6.png)
![image](https://user-images.githubusercontent.com/63871463/222059543-8827d4aa-dfac-4320-9367-d1ed4f2ebe9d.png)

**Environment (please complete the following information):**
 - OS: Windows 11 Pro 21H2
 - Launcher Version: 4.3.2
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**

**Comment by HypedDomi** [comment] 2023-03-01 07:30
Can you send your Logs?
1. Open Solar Tweaks and **enable** `Keep Launcher open`
2. Try to reproduce the error
3. Go to the About tab and click `Download Logs` then click `Open ST directory`
4. Drag and drop the `logs.zip` file into discord

https://cdn.discordapp.com/attachments/866624451398205470/1080122216324268192/SolarTweaks_-_Logs.mp4

**Comment by 770grappenmaker** [comment] 2023-03-01 08:13
Lol if you set /p to /p inv that will create an infinite loop of course

**Comment by 770grappenmaker** [comment] 2023-03-01 11:34
Closing because not a bug, but PEBKAC

**Closed** 2023-03-01 11:34 UTC
Labels: bug
