### ISSUE TITLE
Game Is Crashing When Launching

### ISSUE THREAD

**Issue by D1amondPin** [Solar-Tweaks/Solar-Tweaks#37] opened 2022-04-28 02:13 UTC
Hi.

I have a problem with Solar Tweaks, when I launch the game it loads like normally, when it's done loading, it crashes, it shows 
dirt all over the screen, and stone bricks when I use a Pack. I Downloaded Zulu (applied it), reinstalled Solar Tweaks and even Restarted my PC. I also dont know what a JVM is.

The Version is 1.8.

That's all the information I can provide, I'll provide more information when u guys need something.
![image_2022-04-28_100219965](https://user-images.githubusercontent.com/104540887/165661518-d289f44c-b086-458a-8c7e-a764e33ed5f4.png)

**Comment by D1amondPin** [comment] 2022-04-29 05:26
Log: [latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8588298/latest.log)

**Comment by 770grappenmaker** [comment] 2022-04-29 21:26
Well, logs aren't that useful; today Cy0ze added a feature to actually include game logs so I can actually debug what is going on. Can you provide me with your `%USERPROFILE%\.lunarclient\solartweaks\config.json` file, or would you rather standby until the release which allows for debugging?

**Comment by 770grappenmaker** [comment] 2022-04-30 22:09
Actually can you send me the log with the update?

**Comment by 770grappenmaker** [comment] 2022-05-01 07:37
Duplicate of #58

**Closed** 2022-05-01 07:37 UTC
Labels: support
