### ISSUE TITLE
add heart indector and mods in solar tweks

### ISSUE THREAD

**Issue by senpai64444** [Solar-Tweaks/Solar-Tweaks#1118] opened 2023-04-24 01:24 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by LihanRadit** [comment] 2023-04-24 06:04
bro it is a bug. The Devs R making a new version 4.3.4. It will be realised soon! Just be patient.

**Comment by HypedDomi** [comment] 2023-04-24 08:20
Duplicate of https://github.com/Solar-Tweaks/Solar-Tweaks/issues/1039

**Closed by HypedDomi** 2023-04-24 08:20 UTC
Labels: enhancement

**Comment by senpai64444** [comment] 2023-04-24 10:11
> bro it is a bug. The Devs R making a new version 4.3.4. It will be realised soon! Just be patient.

when

**Comment by HypedDomi** [comment] 2023-04-24 10:13
No ETA

**Comment by HypedDomi** [comment] 2023-04-24 10:13
What you want is not what he means.
