### ISSUE TITLE
Solar Tweaks Freezing

### ISSUE THREAD

**Issue by httphypixelnet** [Solar-Tweaks/Solar-Tweaks#957] opened 2023-03-07 03:18 UTC
**Describe the bug**

**To Reproduce**
1. Go to 'Solar Tweaks'
2. Click on 'Launch 1.8.9'
3. Join any server or singeplayer world
4. Play for a bit

**Expected behavior**
The game runs perfectly 

**Actual behaviour**
Game goes down to 0fps at random points while playing

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 11 Latest Version
 - Launcher Version 4.3.3
 - Engine Version 2.0.9
 - Solar Stats Version (if applicable)
 - GeForce RTX 3060ti 8GB

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports
[logs.zip](https://github.com/Solar-Tweaks/Solar-Tweaks/files/10905066/logs.zip)

**Comment by qualk** [comment] 2023-03-07 06:25
I think this is a duplicate of #710, try add the argument `-XX:+DisableAttachMechanism` in the JVM Arguments section at the bottom of the Settings page. If you use Zulu, it should apply it by default.

Feel free to join the [Discord server](https://discord.gg/solarsocket) for additional support, or if you want to hang out with the community!

**Comment by TheJakobus** [comment] 2023-03-08 15:50
I got the same problem

**Comment by qualk** [comment] 2023-03-08 20:22
> I got the same problem

Well did you try the fix that I posted above? Please try not to post messages that don't contribute into solving the problem.

**Comment by redefault** [comment] 2023-03-09 15:43
instead of adding it completely replace the whole JVM args with `-XX:+DisableAttachMechanism`

**Comment by qualk** [comment] 2023-03-09 22:10
^ Try that, then if it works, try it with the existing arguments.

**Closed** 2023-03-11 00:48 UTC
Labels: support
