### ISSUE TITLE
Skins for no premium

### ISSUE THREAD

**Issue by THEPOTATOKINGQQ** [Solar-Tweaks/Solar-Tweaks#1125] opened 2023-04-24 18:45 UTC
Hello i want a changer for skin for cracked accounts

**Comment by HypedDomi** [comment] 2023-04-24 20:18
Duplicate of #963

**Closed by HypedDomi** 2023-04-24 20:18 UTC
Labels: enhancement

**Comment by BaXyy** [comment] 2023-04-28 14:58
do you have a method to have skin with cracked acc. 
          Thanks
