### ISSUE TITLE
patcher doesnt works

### ISSUE THREAD

**Issue by UzielHDD** [Solar-Tweaks/Solar-Tweaks#36] opened 2022-04-28 01:28 UTC
i have the patcher enabled and the files generate but i dont get the changes in game

![download](https://user-images.githubusercontent.com/89594267/165658036-e24d3b4a-de00-4955-9153-81f645a40bef.png)
i have the skip files thing disabled

**Comment by 770grappenmaker** [comment] 2022-04-28 08:35
Duplicate of #14

**Closed by 770grappenmaker** 2022-04-28 08:35 UTC
Labels: bug
