### ISSUE TITLE
Lag spikes bc of ram going up and up without stopping

### ISSUE THREAD

**Issue by skywlker420** [Solar-Tweaks/Solar-Tweaks#710] opened 2022-12-01 15:41 UTC
**Describe the bug**
SO, ive been using st for while, never get any error, since 4.1 update i think, the ram ussage its just going up and up, till it get to 97% and then the lag spikes happen, after this the ram ussage reset to like 11% and keep going up and up till 97% again, its the same eveytime, lag spikes r so anoyying and this only happen w st, i tried using lc, badlion, vanilla mc, and its not happening, even w the last update of st its the same, i have 8gb of ram so i put 4gbs of ram for st, always use like this and never get error, please fix this

**Environment (please complete the following information):**
 - Windows
 - Solar Tweaks Launcher 4.2 - 4.1 - 4-0

https://user-images.githubusercontent.com/119609308/205095720-ea8c3c1f-40db-405d-91ae-f516a3f0c0cc.mp4

**Comment by UnaPepsi** [comment] 2022-12-02 16:25
has happened to me, fixed by changing the jvm arguments
https://i.imgur.com/0Zsyinx.png
-XX:+DisableAttachMechanism

**Comment by skywlker420** [comment] 2022-12-02 18:39
> 

It worked thank uuuu

**Comment by qualk** [comment] 2022-12-07 23:31
@skywlker420 close the issue if the issue is fixed.

**Closed** 2023-01-26 13:33 UTC
Labels: bug
