### ISSUE TITLE
Solar Tweaks not launching

### ISSUE THREAD

**Issue by MohamedBOIS1** [Solar-Tweaks/Solar-Tweaks#358] opened 2022-06-17 09:05 UTC
Soooo, when I was setting up the JRE zulu, i tried launching the game. i tried using JVM args, launch without them, close, hide or keeping the launcher open doesnt work.
I'm on a windows 10 entreprise so it SHOULD work as intended. but for some reason the launch stops at the discord activity status. you can take a look at my 1.8 logs myself. thats the only version i ever play in there.
[launcher-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8926170/launcher-latest.log)

**Comment by 770grappenmaker** [comment] 2022-06-24 11:09
Duplicate of a discussion thread

**Closed by 770grappenmaker** 2022-06-24 11:09 UTC
Labels: bug
