### ISSUE TITLE
QOL; Feature request

### ISSUE THREAD

**Issue by Luwuf** [Solar-Tweaks/Solar-Tweaks#61] opened 2022-04-29 10:04 UTC
I have a suggestion for the next solar patcher update.

I already suggested the name spoofer which I believe @770grappenmaker is planning on making. However I found another small thing which could make Solar Tweaks far above all other clients which is to be able to use Lunar motion blur's shader while having Fast Render on. Now, I know this is possible because Cheatbreaker has been able to do it and had no trouble. 

It's just a minor detail which is not too significant and it's not a bug, just a suggestion. (Also idk how to remove the bug label)

Thanks

**Comment by 770grappenmaker** [comment] 2022-04-29 21:28
![image](https://user-images.githubusercontent.com/50543283/166071508-d15514f8-e90d-4f0c-88f6-bcf67171b09c.png)
Apparently, not even optifine allows for applying shaders when fast render is on; I don't know what the problem is though. I'll investigate.

**Comment by Luwuf** [comment] 2022-04-29 21:55
Hm apparently Optifine made it a feature to be able to have shaders with fast render past 1.14.2 or something. U might have to modify Optifine or something, I have no idea…

**Comment by 770grappenmaker** [comment] 2022-04-29 21:55
Can't find much taking a quick look at [Decencies's remap](https://github.com/Decencies/CheatBreaker), however I suspect they just allow fast render and have a fix when mixed with any shaderpacks (it probably introduces bugs, why else would fast render be disabled when using shaders?). I'll try removing the fast render conditions and I'll see the results.

**Comment by 770grappenmaker** [comment] 2022-04-29 21:56
Maybe @Decencies can give me some info on how cheatbreaker handles this.

**Comment by 770grappenmaker** [comment] 2022-04-29 21:58
> Hm apparently Optifine made it a feature to be able to have shaders with fast render past 1.14.2 or something. U might have to modify Optifine or something, I have no idea…

Maybe. I'm not too sure if I'll be able to pull this off since it also needs to be compatible with 1.7 probably. I'll see if there is an easy fix, probably not.

**Comment by Luwuf** [comment] 2022-04-29 22:04
I just asked around in the Cheatbreaker 2 discord, and the owner, Tellinq, said fast render disables gram buffers which are required for shaders so they just disabled that on feature.

**Comment by Luwuf** [comment] 2022-04-29 22:04
*frame (not gram)

**Comment by CClamz** [comment] 2022-04-30 00:51
> *frame (not gram)

you can actually edit your comment.
Also, does optifine do it too? Disabling framebuffers when fast render is on with shaders? or they have it completely compatible?

**Comment by Luwuf** [comment] 2022-04-30 01:41
> > *frame (not gram)
> 
> you can actually edit your comment. Also, does optifine do it too? Disabling framebuffers when fast render is on with shaders? or they have it completely compatible? (the 1.14+ one)

Well, what I was saying is the Optifine past 1.14 fixed shaders and made it compatible with fast render, however past versions haven’t been fixed. The Cheatbreaker devs implemented a fix by disabling the feature which disabled frame buffers so reenablinng frame buffers, allowing fast render to be used with shaders such as motion blur.

**Comment by Luwuf** [comment] 2022-04-30 01:44
> > Hm apparently Optifine made it a feature to be able to have shaders with fast render past 1.14.2 or something. U might have to modify Optifine or something, I have no idea…
> 
> Maybe. I'm not too sure if I'll be able to pull this off since it also needs to be compatible with 1.7 probably. I'll see if there is an easy fix, probably not.

How is it going? I think you only need to disable the frame buffer disabler in the fast render section and you don’t need to do much else. That’s the only feature which causes bugs and issues such as GL and render issues with shaders. A quick mod of Optifine should fix it.

**Comment by Luwuf** [comment] 2022-04-30 02:12
Yeah I can’t find out how Optifine did it as I found the issue on github but it gave no info so yeah…
![Uploading 103D0CA3-7226-48A5-A01F-7C370FC05B55.jpeg…]()

**Comment by 770grappenmaker** [comment] 2022-04-30 09:09
> > > Hm apparently Optifine made it a feature to be able to have shaders with fast render past 1.14.2 or something. U might have to modify Optifine or something, I have no idea…
> > 
> > 
> > Maybe. I'm not too sure if I'll be able to pull this off since it also needs to be compatible with 1.7 probably. I'll see if there is an easy fix, probably not.
> 
> How is it going? I think you only need to disable the frame buffer disabler in the fast render section and you don’t need to do much else. That’s the only feature which causes bugs and issues such as GL and render issues with shaders. A quick mod of Optifine should fix it.

I was asleep... I will now take a look at how it works in optifine, but I can't promise anything.

**Comment by 770grappenmaker** [comment] 2022-04-30 09:15
![image](https://user-images.githubusercontent.com/50543283/166099588-f3353398-1abe-4d83-a092-74eef5582afb.png)
This is what seems to be the code that disallows fast render when using shaders. I don't know how disabling frame buffers works and where in the code that happens. I contacted Tellinq to give me some more information.

**Comment by Luwuf** [comment] 2022-04-30 10:28
oops didnt mean to close it, sorry

**Comment by 770grappenmaker** [comment] 2022-05-01 15:25
Seems like Tellinq is ghosting me lol, he did friend me tho

**Comment by Luwuf** [comment] 2022-05-06 05:12
> Seems like Tellinq is ghosting me lol, he did friend me tho

Rip

**Comment by 770grappenmaker** [comment] 2022-05-28 21:51
Since it is actually worthless to do (fast render but you still have a framebuffer = no difference to normal render) and I don't have info, wontfix for now

**Closed** 2022-06-12 07:47 UTC
Labels: enhancement, wontfix
