### ISSUE TITLE
CRASH-0fae970a-8f6c-4681-a160-d25168be1bad Im facing this error 

### ISSUE THREAD

**Issue by Leo1x** [Solar-Tweaks/Solar-Tweaks#1069] opened 2023-04-14 13:51 UTC
when im starting game im facing this error in solar tweaks CRASH-0fae970a-8f6c-4681-a160-d25168be1bad

**Comment by sharifjameel90** [comment] 2023-04-14 16:52
its says game launched
and lunar starts after it loads everything it crashes

**Comment by sharifjameel90** [comment] 2023-04-14 16:54
![iScreen Shoter - Lunar Client - 230414222352](https://user-images.githubusercontent.com/72310282/232108031-c429b0f1-e497-4439-b054-8a40e5d7c1b4.png)

after this it straight crashes

**Comment by HypedDomi** [comment] 2023-04-14 17:41
1. Open Solar Tweaks and **enable** `Keep Launcher open`
2. Try to reproduce the error
3. Go to the About tab and click `Download Logs` then click `Open ST directory`
4. Drag and drop the `logs.zip` file into discord

https://user-images.githubusercontent.com/50876016/222073117-44d61000-002f-4168-99de-5f889b46a082.mp4

**Comment by Leo1x** [comment] 2023-04-15 04:43
where i have to drop logs?

**Comment by sharifjameel90** [comment] 2023-04-15 09:57
> where i have to drop logs?
Step 1: join the solar tweeks discord
Step 2: Create a ticket
Step 3: list your problems, do this method done in the video, then share the logs in ticket

**Comment by HypedDomi** [comment] 2023-04-15 12:44
> where i have to drop logs?

Here or in our Discord when youre in it. I just used the same Video for GitHub and Discord since im lazy

**Comment by HypedDomi** [comment] 2023-04-16 22:50
Fixed in Discord

**Closed by HypedDomi** 2023-04-16 22:50 UTC
Labels: support
